name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: berthcare_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    env:
      # Note: These credentials are safe to hardcode as they only apply to ephemeral
      # GitHub Actions containers that are destroyed after each run. They cannot be
      # used to access any production or persistent infrastructure.
      TEST_DATABASE_URL: postgresql://test_user:test_password@localhost:5432/berthcare_test
      TEST_REDIS_URL: redis://localhost:6379
      # Twilio test credentials (mocked in tests, but needed for initialization)
      TWILIO_ACCOUNT_SID: test_account_sid
      TWILIO_AUTH_TOKEN: test_auth_token
      TWILIO_PHONE_NUMBER: +15550000000
      TWILIO_WEBHOOK_BASE_URL: http://localhost:3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false

      - name: Run Prettier check
        run: npm run format:check
        continue-on-error: false

      - name: Run TypeScript type check
        run: npm run type-check
        continue-on-error: false

      - name: Build shared library
        run: npx nx run shared:build

      - name: Setup test database
        run: |
          cd apps/backend
          npm run migrate:up
        env:
          DATABASE_URL: ${{ env.TEST_DATABASE_URL }}

      - name: Run tests with coverage
        run: npm run test:ci -- --maxWorkers=2
        continue-on-error: false

      - name: Run dependency audit
        run: npm audit --audit-level=high
        continue-on-error: false

      - name: Build all packages
        run: npm run build
        continue-on-error: false

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: CI Summary
        if: always()
        run: |
          echo "✅ All CI checks completed"
          echo "Lint, format, type-check, tests, audit, and build all passed"
