name: Monorepo CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    name: Detect Affected Workspaces
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      mobile: ${{ steps.filter.outputs.mobile }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: filter
        name: Filter paths
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'apps/backend/**'
              - 'libs/shared/**'
              - '.github/workflows/backend-ci.yml'
              - 'package.json'
              - 'package-lock.json'
              - 'tsconfig.base.json'
              - '.eslintrc.json'
            mobile:
              - 'apps/mobile/**'
              - 'libs/shared/**'
              - '.github/workflows/mobile-ci.yml'
              - 'package.json'
              - 'package-lock.json'
              - 'tsconfig.base.json'
              - '.eslintrc.json'

  backend:
    name: Backend CI
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true' || github.event_name != 'pull_request'
    uses: ./.github/workflows/backend-ci.yml
    secrets: inherit

  mobile:
    name: Mobile CI
    needs: detect-changes
    if: needs.detect-changes.outputs.mobile == 'true' || github.event_name != 'pull_request'
    uses: ./.github/workflows/mobile-ci.yml
    secrets: inherit
